server:
  port: 9090

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: root
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/AuthDB
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}